### ISSUE TITLE
UI Component: Live Stream

### ISSUE THREAD

**Issue by austinpray** [liveplant/liveplant.io#8]
As discussed over at http://about.liveplant.io/meetup/progress/2015/05/29/meetup-hashtag-liveplant.html#ui-components

![stream](https://cloud.githubusercontent.com/assets/2192970/7895442/8f04b436-0653-11e5-9b0a-a8e0c285e7a0.jpeg)
- [ ] create twitch.tv account

**Comment by robthedev** [comment]
Twitch account:

name: liveplantio

password: elimanning1

**Comment by austinpray** [comment]
:arrow_up: Lol password changed
